language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: 7.1
    - php: hhvm

before_install:
  - composer selfupdate

addons:
  apt:
    packages:
    - parallel

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ "$DEPENDENCIES" == "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

before_script:
  - echo "<?php if (PHP_VERSION_ID >= 50400) echo ',@php5.4';" > php_version_tags.php

script:
   - ./vendor/bin/phpspec run --format=pretty
   #- ./vendor/bin/phpunit --testdox
   - ./vendor/bin/behat --format=pretty --tags '~@php-version'`php php_version_tags.php`
